# https://helm.sh/docs/chart_template_guide/values_files/

# TODO check the parameters and define our own ones

deployment:
  replicas: 1
  containerPort: 8080
  imagePullSecrets: []
  image: ""
  tag: ""

service:
  port: 80

ingress:
  enabled: false
  class: nginx
  clusterIssuer: letsencrypt-prod
