{{- if .Values.ingress.enabled -}}
{{- $fullName := include "k8s-simple-app.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    {{- with .Values.ingress.extraAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

spec:
  tls:
    - hosts:
        - {{ include "k8s-simple-app.fullDomain" . }}
      secretName: {{ include "k8s-simple-app.tlsSecretName" . }}
  rules:
    - host: {{ include "k8s-simple-app.fullDomain" . }}
      http:
        paths:
          {{- if .Values.ingress.pathPrefixes }}
          {{- range .Values.ingress.pathPrefixes }}
          - backend:
              service:
                  name: {{ $.Release.Name }}
                  port:
                    name: http
            path: {{ . }}
            pathType: Prefix
          {{- end }}
          {{- else }}
          - backend:
              service:
                name: {{ .Release.Name }}
                port:
                  name: http
            path: /
            pathType: Prefix
            {{- end }}
{{- end }}
